version: '3'

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: db-sesuni
    ports:
      - '5444:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sesuni
    volumes:
      - ./data:/var/lib/postgresql/data
